//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Diagrams')
export class DiagramsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('integer', { nullable: true })
  creator: number;

  @Column('date', { nullable: true })
  creationDate: Date;

  @Column('bool', { nullable: true })
  copyPaste: boolean;

  @Column('text', { nullable: true })
  colorOptions: string;

  @Column('text', { nullable: true })
  customLines: string;
}
