//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Meetings')
export class MeetingsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('date', { nullable: true })
  date: Date;

  @Column('date', { nullable: true })
  time: Date;

  @Column('text', { nullable: true })
  agenda: string;

  @Column('integer', { nullable: true })
  participants: number;
}
