//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const MeetingsTitle = () => {
  const record = useRecordContext();
  return <span>Meetings {record ? `"${record.title}"` : ''}</span>;
};

export const MeetingsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="title" />
      <DateField source="date" />
      <DateField source="time" />
      <TextField source="agenda" />
      <ReferenceField source="participants" reference="Users" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const MeetingsEdit = () => (
  <Edit title={<MeetingsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="agenda" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="participants" reference="Users" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const MeetingsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="agenda" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="participants" reference="Users" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="participants"
    label="participants"
    reference="Users"
    alwaysOn
  />,
];
