//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UsersList, UsersCreate, UsersEdit } from './resources/Users';
import {
  MeetingsList,
  MeetingsCreate,
  MeetingsEdit,
} from './resources/Meetings';
import { NotesList, NotesCreate, NotesEdit } from './resources/Notes';
import {
  DiagramsList,
  DiagramsCreate,
  DiagramsEdit,
} from './resources/Diagrams';
import {
  PersonalNotebooksList,
  PersonalNotebooksCreate,
  PersonalNotebooksEdit,
} from './resources/PersonalNotebooks';
import UsersIcon from '@mui/icons-material/Person';
import MeetingsIcon from '@mui/icons-material/Event';
import NotesIcon from '@mui/icons-material/Note';
import DiagramsIcon from '@mui/icons-material/Image';
import PersonalNotebooksIcon from '@mui/icons-material/Book';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a10ad2855">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Users"
          options={{ label: 'Users' }}
          list={UsersList}
          create={UsersCreate}
          edit={UsersEdit}
          recordRepresentation="name"
          icon={UsersIcon}
        />
        <Resource
          name="Meetings"
          options={{ label: 'Meetings' }}
          list={MeetingsList}
          create={MeetingsCreate}
          edit={MeetingsEdit}
          recordRepresentation="title"
          icon={MeetingsIcon}
        />
        <Resource
          name="Notes"
          options={{ label: 'Notes' }}
          list={NotesList}
          create={NotesCreate}
          edit={NotesEdit}
          recordRepresentation="title"
          icon={NotesIcon}
        />
        <Resource
          name="Diagrams"
          options={{ label: 'Diagrams' }}
          list={DiagramsList}
          create={DiagramsCreate}
          edit={DiagramsEdit}
          recordRepresentation="title"
          icon={DiagramsIcon}
        />
        <Resource
          name="PersonalNotebooks"
          options={{ label: 'Personal Notebooks' }}
          list={PersonalNotebooksList}
          create={PersonalNotebooksCreate}
          edit={PersonalNotebooksEdit}
          recordRepresentation="title"
          icon={PersonalNotebooksIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
