//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Yug Yatra" />
    <CardContent>
      A digital platform for a project of sanatan dharam and used by all the
      people who are in the project and have a icon for meeting and an icon for
      notebook which is accessible by everyone and a third icon for diagram work
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
