//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Users: {
      name: 'Users',
      fields: { name: 'Name', email: 'Email', role: 'Role', id: 'id' },
    },
    Meetings: {
      name: 'Meetings',
      fields: {
        title: 'Title',
        date: 'Date',
        time: 'Time',
        agenda: 'Agenda',
        participants: 'Participants',
        id: 'id',
      },
    },
    Notes: {
      name: 'Notes',
      fields: {
        title: 'Title',
        content: 'Content',
        author: 'Author',
        creationDate: 'Creation Date',
        id: 'id',
      },
    },
    Diagrams: {
      name: 'Diagrams',
      fields: {
        title: 'Title',
        description: 'Description',
        creator: 'Creator',
        creationDate: 'Creation Date',
        copyPaste: 'Copy Paste',
        colorOptions: 'Color Options',
        customLines: 'Custom Lines',
        id: 'id',
      },
    },
    PersonalNotebooks: {
      name: 'Personal Notebooks',
      fields: {
        title: 'Title',
        content: 'Content',
        author: 'Author',
        creationDate: 'Creation Date',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        email: 'Email (fr)',
        role: 'Role (fr)',
        id: 'id',
      },
    },
    Meetings: {
      name: 'Meetings (fr)',
      fields: {
        title: 'Title (fr)',
        date: 'Date (fr)',
        time: 'Time (fr)',
        agenda: 'Agenda (fr)',
        participants: 'Participants (fr)',
        id: 'id',
      },
    },
    Notes: {
      name: 'Notes (fr)',
      fields: {
        title: 'Title (fr)',
        content: 'Content (fr)',
        author: 'Author (fr)',
        creationDate: 'Creation Date (fr)',
        id: 'id',
      },
    },
    Diagrams: {
      name: 'Diagrams (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        creator: 'Creator (fr)',
        creationDate: 'Creation Date (fr)',
        copyPaste: 'Copy Paste (fr)',
        colorOptions: 'Color Options (fr)',
        customLines: 'Custom Lines (fr)',
        id: 'id',
      },
    },
    PersonalNotebooks: {
      name: 'Personal Notebooks (fr)',
      fields: {
        title: 'Title (fr)',
        content: 'Content (fr)',
        author: 'Author (fr)',
        creationDate: 'Creation Date (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
